-- MySQL Script generated by MySQL Workbench
-- 03/19/16 20:52:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MedicalClinicManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MedicalClinicManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MedicalClinicManager` DEFAULT CHARACTER SET latin1 ;
USE `MedicalClinicManager` ;

-- -----------------------------------------------------
-- Table `MedicalClinicManager`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedicalClinicManager`.`pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `dataCadastroPessoa` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `nomePessoa` VARCHAR(45) NOT NULL,
  `RgPessoa` VARCHAR(11) NOT NULL,
  `dataEmissaoRgPessoa` DATE NOT NULL,
  `orgaoEmissorRgPessoa` CHAR(6) NOT NULL,
  `cpfPessoa` VARCHAR(15) NOT NULL,
  `dataNascimentoPessoa` DATE NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `nomePessoa_UNIQUE` (`nomePessoa` ASC),
  UNIQUE INDEX `cpfPessoa_UNIQUE` (`cpfPessoa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedicalClinicManager`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedicalClinicManager`.`paciente` (
  `prontuarioPaciente` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `sexoPaciente` ENUM('F', 'M') NOT NULL,
  `estadoCivilPaciente` VARCHAR(25) NOT NULL DEFAULT 'não fornecido',
  `profissaoPaciente` VARCHAR(45) NOT NULL DEFAULT 'não fornecido',
  `escolaridadePaciente` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`prontuarioPaciente`),
  INDEX `fk_paciente_pessoa1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_paciente_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `MedicalClinicManager`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedicalClinicManager`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedicalClinicManager`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NOT NULL,
  `logradouroEndereco` VARCHAR(45) NOT NULL,
  `numeroEndereco` VARCHAR(45) NOT NULL,
  `complementoEndereco` VARCHAR(45) NOT NULL,
  `bairroEndereco` VARCHAR(45) NOT NULL,
  `cidadeEndereco` VARCHAR(45) NOT NULL,
  `CEPEndereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `CEPEndereco_UNIQUE` (`CEPEndereco` ASC),
  UNIQUE INDEX `numeroEndereco_UNIQUE` (`numeroEndereco` ASC),
  INDEX `fk_endereco_pessoa1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `MedicalClinicManager`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedicalClinicManager`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedicalClinicManager`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NOT NULL,
  `telefoneResidencial` VARCHAR(45) NOT NULL,
  `telefoneComercial` VARCHAR(45) NULL,
  `telefoneCelular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_pessoa_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_telefone_pessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `MedicalClinicManager`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedicalClinicManager`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedicalClinicManager`.`email` (
  `idEmail` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NOT NULL,
  `enderecoEmail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idEmail`),
  INDEX `fk_email_pessoa1_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_email_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `MedicalClinicManager`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
